spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/modoospace
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true # sql 콘솔 출력
        format_sql: true # sql 포맷 옵션
        highlight_sql: true # sql 하이라이터 옵션
        default_batch_fetch_size: 100 # 지연로딩 시 in쿼리로 조회가능 (N+1문제 방지)

  config:
    import: application-oauth.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace # 파라미터 binding 값 확인
