spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/modoospace
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false # System.out
        format_sql: true # logger

  config:
    import: application-oauth.yml
