spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/modoospace
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true # System.out
        format_sql: true # logger
        default_batch_fetch_size: 100 # 지연로딩 시 in쿼리로 조회가능 (N+1문제 방지)

  config:
    import: application-oauth.yml
