name: CI

on:
  pull_request:
    branches: [ "develop" ]

permissions: write-all

jobs:
  CI:
    runs-on: ubuntu-latest
    # 작업 실행단계
    steps:
      # 체크아웃 및 JDK 세팅
      - name : Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # Gradle 권한 부여
      - name : Grant Execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      # application.yml 파일 생성
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YAML }}" | base64 --decode > ./application.yml
        shell: bash
      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
      # 테스트커버리지 체크 결과 확인 (Instruction 기준)
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          title: "⭐️Code Coverage"
          update-comment: true