name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    # 작업 실행단계
    steps:
      # 체크아웃 및 JDK 세팅
      - name : Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # Gradle 권한 부여
      - name : Grant Execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      # application.yml 파일 생성
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YAML }}" | base64 --decode > ./application.yml
        shell: bash
      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
      # DockerFile 이미지 작성 및 Docker Repository 업로드
      - name: Docker build & Docker push
        run: |
         docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
         docker build -f Dockerfile -t ${{ secrets.USER_NAME }}/modoospace .
         docker push ${{ secrets.USER_NAME }}/modoospace
